In [4]:
import pandas as pd
df_listed = pd.read_csv("data/CRMLSListing202602.csv")
df_sold = pd.read_csv("data/CRMLSSold202602.csv")

In [3]:
df_listed.head()

,OriginalListPrice,ListingKey,CloseDate,ClosePrice,ListAgentFirstName,ListAgentLastName,Latitude,Longitude,UnparsedAddress,PropertyType,...,MainLevelBedrooms,NewConstructionYN,GarageSpaces,HighSchoolDistrict,PostalCode,BuyerOfficeName.1,AssociationFee,LotSizeSquareFeet,MiddleOrJuniorSchoolDistrict,UnparsedAddress.1
0,599000.0,1155878924,NaN,NaN,Rhonda,Cudeback,33.846885,-118.189492,309 E Silva Street,Residential,...,2.0,False,1.0,Long Beach Unified,90805,NaN,0.0,2250.0,NaN,309 E Silva Street
1,699000.0,1155878603,NaN,NaN,Frances,Mouser,33.587219,-117.177790,27636 Brentstone Way,Residential,...,4.0,NaN,3.0,Murrieta,92563,NaN,0.0,8276.4,NaN,27636 Brentstone Way
2,1250000.0,1155878531,2026-03-24,1250000.0,Marcel,Bonee,33.162238,-117.260161,5086 Corinthia Way,Residential,...,NaN,False,2.0,NaN,92056,Allison James Estates & Homes,755.0,4309.0,NaN,5086 Corinthia Way
3,27000.0,1155877325,NaN,NaN,Georgie,Fenton,33.605898,-117.893620,203 Sapphire,ResidentialLease,...,0.0,False,2.0,Newport Mesa Unified,92662,NaN,0.0,2550.0,NaN,203 Sapphire
4,699000.0,1155873898,NaN,NaN,Ryan,Caron,32.696978,-117.009878,8773 Leigh Ave,Residential,...,NaN,NaN,2.0,Sweetwater Union,91977,NaN,0.0,5800.0,NaN,8773 Leigh Ave

In [5]:
df_sold.head()

,BuyerAgentAOR,ListAgentAOR,Flooring,ViewYN,WaterfrontYN,BasementYN,PoolPrivateYN,OriginalListPrice,ListingKey,CloseDate,...,MainLevelBedrooms,NewConstructionYN,GarageSpaces,HighSchoolDistrict,PostalCode,AssociationFee,LotSizeSquareFeet,MiddleOrJuniorSchoolDistrict,OriginatingSystemName,OriginatingSystemSubName
0,ContraCosta,BayEast,NaN,NaN,NaN,NaN,NaN,1580000.0,1155696412,2026-02-19,...,NaN,NaN,NaN,NaN,95821,0.0,18682.0,NaN,CRMLS,CRMLS_CCBE
1,OrangeCounty,OrangeCounty,"Carpet,Tile",False,NaN,NaN,False,1100000.0,1155620121,2026-02-27,...,3.0,False,2.0,Irvine Unified,92604,NaN,5000.0,NaN,CRMLS,CRMLS_CRM
2,BeverlyHillsGreaterLa,BeverlyHillsGreaterLa,Wood,False,NaN,NaN,False,999000.0,1155350576,2026-02-27,...,NaN,False,NaN,NaN,91411,NaN,12005.0,NaN,CRMLS,CRMLS_CL
3,SanDiego,SanDiego,NaN,NaN,NaN,NaN,NaN,1650000.0,1155221012,2026-02-14,...,NaN,NaN,NaN,NaN,91910,0.0,6851.0,NaN,CRMLS,CRMLS_SAND
4,Newport,Newport,NaN,False,NaN,NaN,False,525000.0,1155192177,2026-02-24,...,4.0,False,0.0,ABC Unified,94510,0.0,18730.0,NaN,CRMLS,CRMLS_CRM